on:
  workflow_dispatch:
jobs:
  package:
    name: Package Extension
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 20.3.1
    - name: Checkout repo
      uses: actions/checkout@v3.5.3
    - name: Build extension
      run: |
        npm install
        npm install --global @vscode/vsce
        bash ./package.sh
    - name: Upload extension
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./dist/*
